{
 "title": "TFG",
 "time": { "from": "2023-12-31T23:00:00.000Z", "to": "2024-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": "SELECT DISTINCT country FROM logs where country != ''"
   },
   { "name": "interval", "label": "interval", "query": "1h,1d,7d,1M" }
  ]
 },
 "panels": [
  {
   "title": "Usuarios Únicos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT $__timeGroup(fecha, $interval) as time, count(distinct usuario) as usuarios FROM logs.logs WHERE $__timeFilter(fecha) GROUP BY time"
    }
   ]
  },
  {
   "title": "Duración Media",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT $__timeGroup(fecha, $interval) as time, AVG(minutos) AS minutos \r\nFROM logs.logs where $__timeFilter(fecha)  GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Eventos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT $__timeGroup(fecha, $interval) as time, count(*) as eventos FROM logs.logs WHERE $__timeFilter(fecha) GROUP BY time ORDER BY TIME"
    }
   ]
  },
  {
   "title": "Paises",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT $__timeGroup(fecha, $interval) as time, count(distinct COUNTRY) as usuarios FROM logs.logs WHERE $__timeFilter(fecha) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Serie temporal",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT\r\n  $__timeGroup(fecha, $interval)  AS time,\r\n  country,\r\n  COUNT(*) AS Total\r\nFROM logs.logs\r\nWHERE $__timeFilter(fecha) AND country is not null and country in ($country)\r\nGROUP BY time, country\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Acumulado Histórico",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT\r\n  $__timeGroup(fecha, '7d')  AS time,\r\n  COUNT(*) AS Total\r\nFROM logs.logs\r\nWHERE $__timeFilter(fecha)  and country in ($country)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Duracion por mes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT \r\n  DATE_FORMAT(Fecha, '%Y-%m') as fecha,\r\n  sum(minutos) AS minutos\r\nFROM logs\r\nWHERE  country in ($country) and $__timeFilter(fecha) \r\nGROUP BY DATE_FORMAT(Fecha, '%Y-%m')\r\nORDER BY fecha;"
    }
   ]
  },
  {
   "title": "Mapa",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT\r\n    logs.lat AS latitude,                             \r\n    logs.lng AS longitude,                           \r\n    COUNT(DISTINCT logs.Usuario) AS unique_users     \r\nFROM logs.logs\r\nWHERE $__timeFilter(logs.Fecha)                   \r\nGROUP BY logs.lat, logs.lng    \r\nORDER BY unique_users DESC                             \r\n"
    }
   ]
  },
  {
   "title": "Actividad por día de la semana y hora",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT\r\n  NombreDia,\r\n  Hora,\r\n  COUNT(Usuario) \r\nFROM logs\r\nWHERE $__timeFilter(Fecha)\r\nGROUP BY NombreDia, hora\r\nORDER BY FIELD(NombreDia, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), hora"
    }
   ]
  },
  {
   "title": "Eventos",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT COUNT(Evento), Evento FROM logs.logs WHERE $__timeFilter(fecha) GROUP BY Evento ORDER BY COUNT(Evento) DESC "
    }
   ]
  },
  {
   "title": "Piezas Más Usadas",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT PIEZA, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND EVENTO = 'AÑADIR_PIEZA' AND catalogo != 'Estandar' \r\nGROUP BY PIEZA ORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Catálogos Más Escogidos",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT CATALOGO, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND EVENTO = 'AÑADIR_PIEZA' AND catalogo != 'Estandar' \r\nGROUP BY CATALOGO ORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Fabricantes Más Escogidos",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT FABRICANTE, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND EVENTO = 'AÑADIR_PIEZA' AND catalogo != 'Estandar' \r\nGROUP BY FABRICANTE ORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Usuarios con más actividad",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT usuario, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND usuario != 'null'\r\nGROUP BY usuario ORDER BY COUNT(*) DESC"
    }
   ]
  }
 ]
}