{
 "title": "TFGFabricante",
 "time": { "from": "2023-12-31T23:00:00.000Z", "to": "2024-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "country",
    "query": "SELECT DISTINCT country FROM logs where country != ''"
   },
   { "name": "interval", "label": "interval", "query": "1h,1d,7d,1M" }
  ]
 },
 "panels": [
  {
   "title": "Usuarios Únicos",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT $__timeGroup(fecha, $interval) as time, count(distinct usuario) as usuarios FROM logs.logs WHERE $__timeFilter(fecha) AND LOWER(fabricante) = LOWER('${__user.login}') GROUP BY time"
    }
   ]
  },
  {
   "title": "Catálogos usados",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT count(distinct catalogo) as usuarios \r\nFROM logs.logs WHERE $__timeFilter(fecha) and lower(fabricante) = lower('${__user.login}')\r\n"
    }
   ]
  },
  {
   "title": "Piezas Añadidas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT count(*) as eventos FROM logs.logs WHERE $__timeFilter(fecha) and lower(fabricante) = lower('${__user.login}')"
    }
   ]
  },
  {
   "title": "Paises",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT count(distinct COUNTRY) as usuarios \r\nFROM logs.logs WHERE $__timeFilter(fecha) and lower(fabricante) = lower('${__user.login}')\r\n"
    }
   ]
  },
  {
   "title": "Serie temporal",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "WITH catalogos AS (\r\n  SELECT catalogo\r\n  FROM logs.logs\r\n  WHERE $__timeFilter(fecha)\r\n    AND catalogo IS NOT NULL\r\n    AND country IN ($country)\r\n    AND LOWER(fabricante) = LOWER('${__user.login}')\r\n  GROUP BY catalogo\r\n  ORDER BY COUNT(*) DESC\r\n  LIMIT 10\r\n)\r\n\r\nSELECT \r\n  $__timeGroup(fecha, $interval) AS time,\r\n  l.catalogo,\r\n  COUNT(*) AS Total\r\nFROM logs.logs l\r\nJOIN catalogos tc ON l.catalogo = tc.catalogo\r\nWHERE $__timeFilter(fecha)\r\n  AND country IN ($country)\r\n  AND LOWER(fabricante) = LOWER('${__user.login}')\r\nGROUP BY time, l.catalogo\r\nORDER BY time, Total DESC;"
    }
   ]
  },
  {
   "title": "Acumulado Histórico",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "WITH piezas AS (\r\n  SELECT pieza\r\n  FROM logs.logs\r\n  WHERE $__timeFilter(fecha)\r\n    AND pieza IS NOT NULL\r\n    AND country IN ($country)\r\n    AND LOWER(fabricante) = LOWER('${__user.login}')\r\n  GROUP BY pieza\r\n  ORDER BY COUNT(*) DESC\r\n  LIMIT 5\r\n),\r\ndatos_agrupados AS (\r\n  SELECT\r\n    $__timeGroup(l.fecha, '$interval') AS time,\r\n    l.pieza,\r\n    COUNT(*) as total_diario\r\n  FROM logs.logs l\r\n  JOIN piezas tp ON l.pieza = tp.pieza\r\n  WHERE $__timeFilter(l.fecha) AND country IN ($country)\r\n    AND LOWER(fabricante) = LOWER('${__user.login}')\r\n  GROUP BY time, l.pieza\r\n)\r\nSELECT\r\n  time,\r\n  pieza,\r\n  total_diario,\r\n  SUM(total_diario) OVER (PARTITION BY pieza ORDER BY time) AS acumulado\r\nFROM datos_agrupados\r\nORDER BY pieza, time;"
    }
   ]
  },
  {
   "title": "Mapa",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT\r\n    logs.lat AS latitude,                             \r\n    logs.lng AS longitude,                           \r\n    COUNT(DISTINCT logs.Usuario) AS unique_users     \r\nFROM logs.logs\r\nWHERE $__timeFilter(logs.Fecha) AND LOWER(fabricante) = LOWER('${__user.login}')                  \r\nGROUP BY logs.lat, logs.lng    \r\nORDER BY unique_users DESC                             \r\n"
    }
   ]
  },
  {
   "title": "Actividad por día de la semana y hora",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT\r\n  NombreDia,\r\n  Hora,\r\n  COUNT(*) \r\nFROM logs\r\nWHERE $__timeFilter(Fecha) and lower(fabricante) = lower('${__user.login}')\r\nGROUP BY NombreDia, hora\r\nORDER BY hora , FIELD(NombreDia, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')"
    }
   ]
  },
  {
   "title": "Catálogos Más Escogidos",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT CATALOGO, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND LOWER(fabricante) = LOWER('${__user.login}')\r\nGROUP BY CATALOGO ORDER BY COUNT(*) DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Piezas Más Usadas",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT PIEZA, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND EVENTO = 'AÑADIR_PIEZA' AND LOWER(fabricante) = LOWER('${__user.login}')\r\nGROUP BY PIEZA ORDER BY COUNT(*) DESC"
    }
   ]
  },
  {
   "title": "Usuarios con más actividad",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "logs",
     "rawSql": "SELECT usuario, COUNT(*) as value FROM logs.logs \r\nWHERE $__timeFilter(FECHA) and country in ($country) AND usuario != 'null'  AND LOWER(fabricante) = LOWER('${__user.login}')\r\nGROUP BY usuario ORDER BY COUNT(*) DESC"
    }
   ]
  }
 ]
}